log_level = "error"
pidfile = '/tmp/clientSIP.pid'
apikey = ''
callback = ''
cycle = 0.3
socketport = 8080
PhoneStatus = None
CallStatus = None
CallMessages = None
Voice = 'fr-FR' #[ 'de-DE', 'en-GB', 'en-US', 'es-ES', 'fr-FR', 'it-IT' ]
